### ISSUE TITLE
Lägg till följande cheetssheets som stöd vid tenta och under kursen

### ISSUE THREAD

**Issue by MansMeg** [STIMALiU/KursRprgm#13]
https://www.rstudio.com/resources/cheatsheets/?mkt_tok=3RkMMJWWfF9wsRonuanIZKXonjHpfsX56u8tWaW0lMI%2F0ER3fOvrPUfGjI4ARcVmI%2BSLDwEYGJlv6SgFTbDMMa541LgKWxc%3D

**Comment by MansMeg** [comment]
@josefwilzen 
Se dessa cheatsheets också.

**Comment by josefwilzen** [comment]
Det ser bra ut, jag lägger ut en länk dit från kurshemsidan.

**Comment by josefwilzen** [comment]
vi diskuterar i #15  så jag stänger här.
