### ISSUE TITLE
oddsconverter funktion, if, else

### ISSUE THREAD

**Issue by jeckjeck** [STIMALiU/KursRprgm#21]
En funktion som konverterar amerikanska odds till europeiska (decimal odds)

Amerikanska odds är antingen negativa eller positiva.

De positiva oddsen visar hur mycket nettovinst spelaren gör när 100 enheter är spelad.

De negativa visar hur mycket en spelare måste satsa för att göra en nettovinst på 100 enheter.

T ex spelas 100 kr till -155 blir nettovinsten vid vinst: 65 kr.
spelas det till oddset 155 blir nettovinsten, just precis 155.

Europeiska- eller decimal odds visar hur mycket vinst inkl. insats spelaren kommer göra, multiplicerat med insats.

T ex oddset 100 kr på 1,65 ger en nettovinst på 65 kr.
100 kr till oddset 2,55 ger nettovinst på 155 kr.

**Comment by MansMeg** [comment]
Tack! Jag har nu noterat denna i vår lista över potentiella uppgifter/tentafrågor. Tack!!
